name: Update Facebook Catalog Feed

on:
  schedule:
    - cron: '5 * * * *'   # ⏰ every hour at :05 UTC
  workflow_dispatch:       # manual run button

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed so the workflow can commit/push

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests certifi

      - name: Generate candidate XML
        run: |
          python generate_feed_xml.py

      - name: Validate candidate XML exists and is non-empty
        run: |
          test -s facebook_catalog_feed_new.xml

      - name: Basic XML sanity check
        run: |
          set -e
          # require at least one <listing> and required tags
          grep -q "<listing>" facebook_catalog_feed_new.xml
          grep -q "<vehicle_id>" facebook_catalog_feed_new.xml
          grep -q "<vin>" facebook_catalog_feed_new.xml
          echo "Candidate XML looks sane."

      - name: Promote candidate -> live (atomic)
        run: |
          cp -f facebook_catalog_feed_new.xml facebook_catalog_feed.xml
          echo "Promoted candidate to live."

      - name: Commit and push if XML changed
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add facebook_catalog_feed.xml
          if ! git diff --cached --quiet; then
            git commit -m "🤖 Auto-update XML feed"
            git push origin master
          else
            echo "No change in live XML; nothing to commit."
          fi
