name: Update Facebook Catalog Feed

on:
  schedule:
    - cron: '0 * * * *'    # ⏰ Every hour (UTC)
  workflow_dispatch:       # ✅ Allow manual run button

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate XML Feed
        run: python generate_feed_xml.py

      - name: Commit and Push if XML Changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add facebook_catalog_feed.xml
          git diff --cached --quiet || git commit -m "🤖 Auto-update XML feed"
          git push
